inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'data/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'plugin/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  ProceduralMethods:
    - benchmark
    - bm
    - bmbm
    - create
    - each_with_object
    - measure
    - new
    - realtime
    - tap
    - with_object
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
  IgnoredMethods:
    - lambda
    - proc
    - it

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: single_quotes