inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'data/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'plugin/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Style/ClassAndModuleChildren:
  EnforcedStyle: nested