clients :
  # Twitter
  twitter :
    client : "BlogNotification::Client::TwitterClient"

    # 設定
    # CK,CS,AT,ATS
    config :
      consumer_key        : ""
      consumer_secret     : ""
      access_token        : ""
      access_token_secret : ""

  # Slack
  slack :
    client : "BlogNotification::Client::SlackClient"

    # tokenとチャンネル名を設定
    config :
      token   : ""
      channel : ""

data :
  dump :
    file : "data/dump.json"

# levels : fatal,error,warn,info,debug
logs:
  debug-log:
    file: 'log/debug.log'
    level: 'debug'

  info-log:
    file: 'log/info.log'
    level: 'info'

urls :
  雨宮天 :
    rss : "http://feedblog.ameba.jp/rss/ameblo/amamiyasorablog/rss20.xml"

  麻倉もも :
    rss : "http://feedblog.ameba.jp/rss/ameblo/asakuramomoblog/rss20.xml"

  夏川椎菜 :
    rss : "http://feedblog.ameba.jp/rss/ameblo/natsukawashiinablog/rss20.xml"