clients :
  # Twitter
  twitter :
    client : "TrySailBlogNotification::Client::TwitterClient"

    # 設定
    # CK,CS,AT,ATS
    config :
      consumer_key        : ""
      consumer_secret     : ""
      access_token        : ""
      access_token_secret : ""

  # Slack
  slack :
    client : "TrySailBlogNotification::Client::SlackClient"

    # tokenとチャンネル名を設定
    config :
      token   : ""
      channel : ""

data :
  log :
    file  : "log/log.log"
    level : :debug

  dump :
    file : "data/dump.json"

urls :
  雨宮天 :
    url : "https://ameblo.jp/amamiyasorablog/"
    parser : "TrySailBlogNotification::Parser::SoraAmamiya"

  麻倉もも :
    url : "https://ameblo.jp/asakuramomoblog/"
    parser : "TrySailBlogNotification::Parser::MomoAsakura"

  夏川椎菜 :
    url : "https://ameblo.jp/natsukawashiinablog/"
    parser : "TrySailBlogNotification::Parser::ShiinaNatsukawa"