name: Ruby CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.6, 2.7]

    steps:
      - uses: actions/checkout@v1

      - name: Use Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - run: bundle install --jobs=4

      - run: bundle exec rspec
        env:
          CI: true

      - name: Slack Notification
        uses: homoluctus/slatify@v1.5
        if: always()
        with:
          job_name: '*${{ github.workflow }}*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
